spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sleuth:
    sampler:
      probability: 1.0  # 采样率(1.0表示100%)
  zipkin:
    base-url: http://host.docker.internal:9411    # 你的 Zipkin Server 地址
    sender:
      type: web                        # 用 HTTP 方式上报

server:
  port: 8081

logging:
  level:
    com.example.demo: debug

feign:
  circuit breaker:
    enabled: true  # 启用Resilience4j支持

resilience4j:
  circuit breaker:
    instances:
      orderService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  rate limiter:
    instances:
      orderLimiter:
        limitForPeriod: 3        # 每秒最多3个请求
        limitRefreshPeriod: 1s
        timeoutDuration: 0